spring:
  application:
    name: report-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/reportdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  kafka:
    bootstrap-servers: localhost:9092
    topic: report-requests
    consumer:
      group-id: report-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

app:
  contact-service:
    url: http://localhost:8081

server:
  port: 8082

logging:
  level:
    com.phonebook_system: DEBUG
    org.hibernate.SQL: DEBUG
